version: '3.8'
services:
  mkdocs:
    build: .
    # image: squidfunk/mkdocs-material
    # command: --serve
    volumes:
      - .:/docs
    ports:
      - "8000:8000"
    environment:
      - PWD=/docs
    stdin_open: true
    tty: true


# http://localhost:8000/mkdocs-material/